### ISSUE TITLE
Network traffic generated upon newkey

### ISSUE THREAD

**Issue by jayliew** [phish108/node-jose-tools#128] opened 2021-03-25 14:15 UTC
Hello!

I was curious about the network traffic that is emitted every single time I run `newkey` with `npx`.

1. What is it for?
2. Is there any way to disable it and make this a 100% offline operation?

Cheers.

**Comment by phish108** [comment] 2021-03-25 21:07
Hi @jayliew 

Not sure if this is related to node-jose-tools or if it is an artefact of npx.

The tools should only run network requests, if a URL is provided for a key store or a key. So if you simply run `jose newkey -r` there shouldn't be any network traffic. 

I run `jose newkey` and all the other tools offline without problems, but I do not use npx in that case. I ran a check and couldn't see any traffic that I was able to trace to node-jose-tools. 

Could you please provide more information how to reproduce that behaviour and trace it back to node-jose-tools?

And since you are already there, please check if the network traffic remains present after installing the module properly?

Thanks

**Comment by jayliew** [comment] 2021-03-26 18:05
I'm not using anything that requires a network connection.

I am running `newkey` with npx, but I'm not familiar with how `npx` or `node-jose-tools` work, that's why I just wanted to bring it up. I don't know what, where, or why there is network traffic.

I did notice that `newkey` will work just fine even without a network connection. Please feel free to close this if this is specific to `npx` and not `node-jose-tools`. 

I was posting here just in case there's anything that can be done from here to disable that network traffic.

**Comment by phish108** [comment] 2021-03-26 18:14
Thanks for the feedback. 

The case with `npx` is that it checks on npm for possible updates. Not sure if it also triggers stats. 

I ran the code through the debugger an in a normal setup it did not hit any network related function. So i can rule out node-jose-tools as the source of the traffic you see.

**Comment by phish108** [comment] 2021-03-26 18:15
Closing issue. Thanks for bringing this up. I did learn a bit while digging.

**Closed** 2021-03-26 18:15 UTC
